### ISSUE TITLE
Move the documentation into ReadTheDocs

### ISSUE THREAD

**Issue by jason-fox** [Introsys/FIREFIT.ROSE-AP#2]
There is a ReadTheDocs project associated with this repo, but the `docs` folder has been deleted therefore no documentation is being built.

Much of the information from `./gcn/docs` and `./icn/docs` should be moved to `./docs` and an `mkdocs.yml` and `.readthedocs.yml` re-introduced

This will autobuild the docs at https://firefitrose-ap.readthedocs.io/en/latest/

The `https://github.com/Introsys/FIREFIT.ROSE-AP/blob/master/mkdocs.yml` needs updating and the placeholder values at the head of the file replaced:

```yaml
site_name: <site-name>
site_url: https://<site-url>
repo_url: https://github.com/<repo_url>
site_description: RAMP Documentation
docs_dir: docs
```

see: https://www.mkdocs.org/#adding-pages on how to add pages
