### ISSUE TITLE
docker-compose references images which are not public

### ISSUE THREAD

**Issue by jason-fox** [Introsys/FIREFIT.ROSE-AP#3]
The `docker-compose` include the following:

```yaml
  # GCN
  gcn:
    image: gcn
    hostname: gcn
    container_name: gcn

  # ICN
  icn:
    image: icn
    hostname: icn
    container_name: icn
```

Neither `icn` nor `gcn` is publicly available on https://hub.docker.com/u/magnoguedes
